# Generated by Django 5.2.1 on 2025-05-16 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="ProductType",
            fields=[
                (
                    "product_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[("AMAZON", "Amazon"), ("GOOGLE", "Google")],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "product_types",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question_text", models.TextField()),
                ("time_limit", models.IntegerField(default=13)),
                ("is_product_question", models.BooleanField(default=False)),
                ("hint", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tool.category",
                    ),
                ),
                (
                    "product_type",
                    models.ForeignKey(
                        blank=True,
                        db_column="product_type_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tool.producttype",
                    ),
                ),
            ],
            options={
                "db_table": "questions",
            },
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                ("option_id", models.AutoField(primary_key=True, serialize=False)),
                ("option_text", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tool.question",
                    ),
                ),
            ],
            options={
                "db_table": "options",
            },
        ),
    ]
